name: Daily report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

env:
  TZ: 'Asia/Shanghai'

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - run:
        export COOKIES=${{ secrets.COOKIES }} \
        pip install --upgrade pip \
        pip install -r requirements.txt \
        python -u src/main.py
